global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'payments-dev'
    environment: 'local'

scrape_configs:
  - job_name: 'payments-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
